############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Categories"
url = "/categories"
weight = 2

[[main]]
name = "Tags"
url = "/tags"
weight = 3

[[main]]
name = "Authors"
url = "/authors"
weight = 4

